service: tartarus

image: your-user/tartarus

servers:
  web:
    - 192.168.0.1

registry:
  username: your-user

  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY

volumes:
  - "tartarus_storage:/rails/storage"

asset_path: /rails/public/assets
